version: '3'
services:
  namenode:
    image: bde2020/hadoop-namenode
    container_name: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - CLUSTER_NAME=test
    volumes:
      - namenode:/hadoop/dfs/name
    networks:
      - hadoop

  datanode:
    image: bde2020/hadoop-datanode
    container_name: datanode
    ports:
      - "9864:9864"
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CORE_CONF_hadoop_http_staticuser_user=root
      - HDFS_CONF_dfs_replication=1
    volumes:
      - datanode:/hadoop/dfs/data
    networks:
      - hadoop

  resourcemanager:
    image: bde2020/hadoop-resourcemanager
    container_name: resourcemanager
    ports:
      - "8088:8088"
    environment:
      - CLUSTER_NAME=test
      - YARN_CONF_yarn_log___aggregation___enable=true
      - YARN_CONF_yarn_log___aggregation___retention___seconds=2592000
      - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    networks:
      - hadoop

  nodemanager:
    image: bde2020/hadoop-nodemanager
    container_name: nodemanager
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
    networks:
      - hadoop

  hive:
    image: bde2020/hive
    container_name: hive
    ports:
      - "10000:10000"
      - "10002:10002"
    environment:
      - HIVE_CONF_hive_metastore_uris=thrift://hive-metastore:9083
      - HIVE_CONF_hive_metastore_warehouse_dir=/user/hive/warehouse
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HIVE_METASTORE_HOST=hive-metastore-postgresql
      - HIVE_METASTORE_PORT=5432
      - HIVE_METASTORE_DB=metastore
      - HIVE_METASTORE_USER=hive
      - HIVE_METASTORE_PASSWORD=hive
    depends_on:
      - namenode
      - datanode
      - resourcemanager
      - nodemanager
      - hive-metastore-postgresql
    networks:
      - hadoop

  hive-metastore-postgresql:
    image: postgres:12
    container_name: hive-metastore-postgresql
    environment:
      - POSTGRES_DB=metastore
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
    volumes:
      - hive-metastore-postgresql:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - hadoop

  pig:
    image: fluddeni/hadoop-pig
    container_name: pig
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    networks:
      - hadoop

volumes:
  namenode:
  datanode:
  hive-metastore-postgresql:

networks:
  hadoop:
    driver: bridge
