version: '3'
services:
  hadoop-spark-pig-hive:
    image: suhothayan/hadoop-spark-pig-hive:2.9.2
    ports:
      - "50070:50070"
      - "8088:8088"
      - "8080:8080"
    stdin_open: true
    tty: true
