version: '3'
services:
  namenode:
    image: bde2020/hadoop-namenode
    container_name: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - CLUSTER_NAME=test
    volumes:
      - namenode:/hadoop/dfs/name
    networks:
      - hadoop

  datanode:
    image: bde2020/hadoop-datanode
    container_name: datanode
    ports:
      - "9864:9864"
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CORE_CONF_hadoop_http_staticuser_user=root
      - HDFS_CONF_dfs_replication=1
    volumes:
      - datanode:/hadoop/dfs/data
    networks:
      - hadoop

  resourcemanager:
    image: bde2020/hadoop-resourcemanager
    container_name: resourcemanager
    ports:
      - "8088:8088"
    environment:
      - CLUSTER_NAME=test
      - YARN_CONF_yarn_log___aggregation___enable=true
      - YARN_CONF_yarn_log___aggregation___retention___seconds=2592000
      - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    networks:
      - hadoop

  nodemanager:
    image: bde2020/hadoop-nodemanager
    container_name: nodemanager
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
    networks:
      - hadoop

  spark-master:
    image: bde2020/spark-master
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    networks:
      - hadoop

  spark-worker:
    image: bde2020/spark-worker
    container_name: spark-worker
    ports:
      - "8081:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8081
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    networks:
      - hadoop

  pig:
    image: fluddeni/hadoop-pig
    container_name: pig
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    networks:
      - hadoop

volumes:
  namenode:
  datanode:

networks:
  hadoop:
    driver: bridge
